### ISSUE TITLE
do you have godot 4 version of this shader?

### ISSUE THREAD

**Issue by mujtaba-io** [mightymochi/2D-Cel-Toon-Shader-v2-Plus#1]
hi. i tried to port it to godot 4, but i think its not as straightforward. - it'll be really useful if u already got godot 4 version of this shader.

**Comment by mightymochi** [comment]
I’ll look into it.

**Comment by mightymochi** [comment]
I was able to get the basic cel shading working in Godot 4. 
[2D-Cel-Shader-Godot-4.x](https://github.com/mightymochi/2D-Cel-Shader-Godot-4.x/blob/main/cel_shader_basic_g4.gdshader)

However they have changed or restricted the properties that we're able to modify in shaders so most of the advanced features(Z-depth, modulating before light, rim_light, spot light, etc) are not working in Godot 4.

**Comment by mightymochi** [comment]
I'll continue to investigate if more features can be brought back, but I'm closing this issue for now as I got the basic cel shader working.

**Comment by mightymochi** [comment]
Actually looks like light height will be doable so I'll update that.
